x-templates:
  default-variables: &default-variables
    TZ: UTC
  default-service: &default-service
    restart: unless-stopped
    tty: true
    stdin_open: true
    init: true
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      <<: *default-variables
  as-current-user: &as-current-user
    user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000}

services:

  # WG
  app:
    <<:
      - *default-service
      - *as-current-user
    image: wg
    build:
      context: .
      args:
        CARGO_BUILD_ARGS: "" # disable release build and use debug build instead
    container_name: wg-app
    environment:
      RUST_LOG: debug
      RUST_BACKTRACE: 1
      PORT: 80
      SMTP_URL: smtp://mailpit:1025
      MAIL_FROM: test@localhost
      # LOW_SCORE_REMINDER_CRON: "*/30 * * * * *"
    volumes:
      - ./data:/data
    ports:
      - "80:80"
    networks:
      - app

  # Local SMTP server
  mailpit:
    <<: *default-service
    image: axllent/mailpit:latest
    container_name: wg-mailpit
    ports:
      - "8025:8025"
    networks:
      - app

networks:
  app:
    driver: bridge
